version: '3.5'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - /api/.env
    container_name: postgres
    volumes:
      - ./api/misc/init-db:/docker-entrypoint-initdb.d
      - ./api/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nest-api
    env_file:
      - ./api/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    networks:
      - app-network
  
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: dev
    container_name: next-app
    env_file:
      - ./web/.env
    ports:
      - '80:3000'
    depends_on:
      - api
    volumes:
      - ./web:/app
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - app-network