-- CREATE TABLE ad_categories (
--     id SERIAL PRIMARY KEY,
--     title VARCHAR(255),
--     alias VARCHAR(255),
--     parent_id INTEGER,
--     translation_key VARCHAR(255),
--     date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (parent_id) REFERENCES ad_categories(id)
-- );

-- CREATE TABLE ad_items (
--     id SERIAL PRIMARY KEY,
--     title VARCHAR(255),
--     alias VARCHAR(255),
--     parent_id INTEGER,
--     translation_key VARCHAR(255),
--     date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
