import type { Metadata } from "next";
import { MODAL_ROOT } from "@/constants";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <div id={MODAL_ROOT} />
      </body>
    </html>
  );
}
