version: '3.5'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: postgres
    volumes:
      - ./misc/init-db:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres